In [ ]:
import numpy as np
## create arrays
### 1D array
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)

## 2d Array
arr2=arr1.reshape(2,3)
print(arr2)
print(arr2.ndim)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)
1
6
[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr1=np.arange(1,10,2).reshape(1,5)
arr1

array([[1, 3, 5, 7, 9]])

In [19]:
np.ones((3,4))
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr1.dtype

dtype('int64')

In [22]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
print("addition",arr1+arr2)
print("sub",arr1-arr2)
print("mul",arr1*arr2)

addition [11 22 33 44 55]
sub [ -9 -18 -27 -36 -45]
mul [ 10  40  90 160 250]


In [25]:
### universal functions 
arr=np.array([2,3,4,5,6,7,8])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974 2.64575131
 2.82842712]
[   7.3890561    20.08553692   54.59815003  148.4131591   403.42879349
 1096.63315843 2980.95798704]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154]


In [43]:
### array slicing and indexing
arr1=np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(3,4)
print(arr1)
print(arr1[0][0])
print(arr1[1:,2:])
print(arr1[:2,2:])
print(arr1[1:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [46]:
arr1[:,3]=100
print(arr1)

[[  1   2   3 100]
 [  5   6   7 100]
 [  9  10  11 100]]


In [49]:
### statistical concepts -Normalization
mean=np.mean(arr1)
print(mean,std_dev)
median=np.median(arr1)
print(median)
print(np.var(arr1))
std_dev=np.std(arr1)
normalized_data=(arr1-mean)/std_dev
print("Normalized data",normalized_data)

29.5 40.80747480548141
8.0
1665.25
Normalized data [[-0.69840146 -0.67389615 -0.64939083  1.72762467]
 [-0.6003802  -0.57587489 -0.55136957  1.72762467]
 [-0.50235895 -0.47785363 -0.45334832  1.72762467]]


In [54]:
arr1[(arr1>5) & (arr1<=8)]

array([6, 7])